
server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduation_project?serverTimezone=GMT%2b8
    username: root
    password: 123456
  main:
    # 默认为false,不支持循环依赖，改为true后可注入循环依赖
    allow-circular-references: true

mybatis:
  mapper-locations: classpath:mapper/*.xml #????mybatis?xml??
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: E:/graduation-project/springboot/springboot/files/
evidences:
  upload:
    path: E:/graduation-project/springboot/springboot/evidences/